_cms_admin:
    resource: "@NfqCmsPageBundle/Resources/config/routing_admin.yml"
    prefix: /admin/cms-pages
    options: { i18n: false }

_cms_front:
    resource: "@NfqCmsPageBundle/Resources/config/routing_front.yml"
    prefix: /
